---
title: "File Retrieval"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{File Retrieval}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(glitter)
library(tidyverse)
library(rlang)
```

# HELP!  
I lost a file my repo but I forgot what I called it so I get a list of all the files ever deleted in the repo.

```{r, eval=TRUE}

deletedFileHistory()

```

I find my long lost file on the list as `R/logo.R`. I then get the commit history of that file using the full path. 

```{r, eval=TRUE}

fileCommitHistory(filePath = "R/logo.R",
                  repo_path = "~/GitHub/Public-Packages/glitter/")

```


I find the commit SHA where I deleted the file. Using the SHA and path, I am able to retrieve the file. 

```{r, eval=FALSE}
retrieveLostFile(sha = "1b9ac7e47fc77f12c21ed2447a71ae8d77a0f37c",
                 filePath = "R/logo.R",
                 repo_path = "~/GitHub/Public-Packages/glitter")
```


